### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by pombredanne** [CERTCC/labyrinth#11]
The only licensing info I could find is in the setup "license="all rights reserved",... can you clarify what is the license for this repo?

**Comment by ahouseholder** [comment]
Fixed by 13c3ec8af85f36e03e29f09f060927f0bf2a7859

Sorry it took so long to resolve this, this project had been on autopilot for a while. The answer is that it's MIT-license compatible, with a few extra words that have to be included because CMU has lawyers.

**Comment by pombredanne** [comment]
@ahouseholder Thank you ++ :bow:
